#!/usr/bin/env python3
"""Regenerate a CORECONF SOR from the canonical OpenSCHC corpus.

This tool imports RuleManager directly from either a caller-supplied rule2sor
checkout or the installed Python package. It never writes the committed SOR
unless the caller explicitly chooses that path as --output.
"""

from __future__ import annotations

import argparse
import importlib
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
CORE_DIR = REPO_ROOT / "fixtures" / "core"
DEFAULT_RULES = CORE_DIR / "core.json"
DEFAULT_SID = CORE_DIR / "ietf-schc@2026-05-07.sid"
COMMITTED_SOR = CORE_DIR / "core.sor"


def add_rule2sor_root(root: Path) -> None:
    """Make a rule2sor checkout importable without changing that checkout."""
    root = root.expanduser().resolve()
    candidates = [root]
    if (root / "__init__.py").is_file():
        candidates.append(root.parent)
    for candidate in reversed(candidates):
        sys.path.insert(0, str(candidate))


def load_rule_manager(rule2sor_root: Path | None):
    """Load RuleManager from a checkout or the installed package."""
    if rule2sor_root is not None:
        add_rule2sor_root(rule2sor_root)
    try:
        module = importlib.import_module("rule2sor.gen_rulemanager")
    except ImportError as error:
        source = f" from {rule2sor_root}" if rule2sor_root else ""
        raise SystemExit(
            f"unable to import rule2sor.gen_rulemanager{source}: {error}"
        ) from error
    return module.RuleManager


def assert_fixture_count() -> None:
    """Prevent this helper from silently growing the canonical fixture set."""
    files = [path for path in CORE_DIR.iterdir() if path.is_file()]
    if len(files) != 4:
        raise SystemExit(
            f"expected exactly four fixtures under {CORE_DIR}, found {len(files)}"
        )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--rule2sor-root",
        type=Path,
        help="rule2sor checkout root or package directory; omit to use installed package",
    )
    parser.add_argument("--rules", type=Path, default=DEFAULT_RULES)
    parser.add_argument("--sid", type=Path, default=DEFAULT_SID)
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="explicit output or temporary path; this tool never chooses a committed path",
    )
    parser.add_argument(
        "--compare",
        type=Path,
        help="compare the generated bytes against this path after writing output",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    assert_fixture_count()
    rule_manager_type = load_rule_manager(args.rule2sor_root)

    manager = rule_manager_type()
    manager.Add(file=str(args.rules), device="test:device1")
    manager.add_sid_file(str(args.sid))
    sor = manager.to_coreconf()

    args.output.expanduser().resolve().parent.mkdir(parents=True, exist_ok=True)
    args.output.write_bytes(sor)
    print(f"wrote {args.output} ({len(sor)} bytes)")

    if args.compare is not None:
        expected = args.compare.read_bytes()
        if sor != expected:
            print(f"byte mismatch: generated output differs from {args.compare}", file=sys.stderr)
            return 1
        print(f"byte-identical to {args.compare}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
